Laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'DashboardController@dashboard')->name('admin.index');
    Route::resource('/message', 'MessageController', ['as' => 'admin']);
    Route::resource('/article', 'ArticleController', ['as' => 'admin']);
});

Route::get('/', 'PostsController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/send', 'mailController@send');

Laravel/app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
use function PMA\Util\get;

class Article extends Model
{
    protected $fillable = [
        'title',
        'slug',
        'description_short',
        'description',
        'image',
        'image_show',
        'meta_title',
        'meta_description',
        'meta_keyword',
        'created_by',
        'modified_by'
    ];

    public function setSlugAttribute($value)
    {
        $this->attributes['slug'] = Str::slug( mb_substr($this->attributes['title'], 0, 40) . "-" . \Carbon\Carbon::now()->format('dmyHi'), '-');
    }

    public function scopeLastArticles($query, $count) {
        return $query->orderBy('created_at', 'desc')->take($count)->get();
    }
}

Laravel/app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
use function PMA\Util\get;

class Post extends Model
{
    public function scopeLastArticles($query, $count)
    {
        return $query->orderBy('created_at', 'desc')->take($count)->get();
    }

}

Laravel/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

Laravel/app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Article;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.articles.index', [
            'articles' => Article::orderBy('created_at', 'desc')->paginate(16)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.articles.create', [
            'article' => [],
            'delimiter' => ''
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $article = Article::create($request->all());
        return redirect()->route('admin.article.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function show(Article $article)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function edit(Article $article)
    {
        return view('admin.articles.edit', [
            'article' => $article,
            'delimiter' => ''
    ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Article $article)
    {
        $article->update($request->except('slug'));
        return redirect()->route('admin.article.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function destroy(Article $article)
    {
        $article->delete();
        return redirect()->route('admin.article.index');
    }
}

Laravel/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

Laravel/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return redirect()->route('admin.article.index');
    }
}

Laravel/app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Article;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PostsController extends Controller
{
    public function index()
    {
        return view('posts.index', [
            'articles' => Article::orderBy('created_at', 'desc')->paginate(16),
            'count_articles' => Article::count(),
        ]);
    }

    public function show()
    {
        return view('posts.show');
    }

}

Laravel/app/Http/Controllers/mailController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Mail;

class mailController extends Controller
{
    public function send()
    {
        Mail::send(['text' => 'mail'], ['name', 'test blog'], function ($message){
            $message->to('jepone1997@gmail.com', 'to web dev blog')->subject('test email');
            $message->from('jepone1997@gmail.com', 'to web dev blog');
    });
    }
}

Laravel/resources/views/admin/articles/create.blade.php
@extends('layout')

@section('content')

    <form action="{{route('admin.article.store')}}" class="form-horizontal" method="post">
        {{ csrf_field() }}

        {{-- Form iclude --}}
        @include('admin.articles.partials.form')
        <input type="hidden" name="created_by" value="{{Auth::id()}}">
    </form>

@endsection

Laravel/resources/views/admin/articles/edit.blade.php
@extends('layout')

@section('content')

    <form action="{{route('admin.article.update', $article)}}" class="form-horizontal" method="post">
        <input type="hidden" name="_method" value="put">
        {{ csrf_field() }}

        {{-- Form iclude --}}
        @include('admin.articles.partials.form')
        <input type="hidden" name="modified_by" value="{{Auth::id()}}">
    </form>

@endsection

Laravel/resources/views/admin/articles/index.blade.php
@extends('layout')

@section('content')

    <div class="container">
        <div class="container">
            <table class="table">
                <thead class="thead-dark">
                <tr>
                    <th scope="col" class="text-left">Наименование</th>
                    <th scope="col">Краткое описание</th>
                    <th scope="col" class="text-right">Действие</th>
                </thead>
                <tbody>

                @forelse($articles as $article)
                    <tr>
                        <td>{{ $article->title }}</td>
                        <td>{{ $article->description_short }}</td>
                        <td class="text-right">

                            <form onsubmit="if(confirm('Удалить?')) {return true} else {return false}"
                                  action="{{route('admin.article.destroy', $article)}}" method="post">

                                <input type="hidden" name="_method" value="DELETE">
                                {{csrf_field()}}

                                <a class="btn btn-default" href="{{route('admin.article.edit', $article)}}"><i
                                        class="fa fa-edit"></i></a>

                                <button type="submit" class="btn"><i class="fa fa-trash-o"></i></button>
                            </form>
                        </td>
                    </tr>

                @empty
                    <tr>
                        <td colspan="3" class="text-center"><h2>Данные отсутствуют</h2></td>
                    </tr>
                @endforelse
                </tbody>
            </table>
        </div>

        <div class="container">
            <table class="table">
                <tfoot>
                <td colspan="3">
                    <ul class="float-right">
                        {{$articles->links()}}
                    </ul>
                </td>
                </tfoot>
            </table>
        </div>
    </div>

@endsection

Laravel/resources/views/admin/articles/partials/form.blade.php
<div class="container">


    <label for="">Заголовок</label>
    <input type="text" class="form-control" name="title" placeholder="Заголовок новости"
           value="{{$article->title ?? ""}}"
           required>

    <label for="">Slug (Уникальное значение)</label>
    <input class="form-control" type="text" name="slug" placeholder="Автоматическая генерация"
           value="{{$article->slug ?? ""}}" readonly="">

    <label for="">Краткое описание</label>
    <textarea class="form-control" id="description_short"
              name="description_short">{{$article->description_short ?? ""}}</textarea>

    <label for="">Полное описание</label>
    <textarea class="form-control" id="description" name="description">{{$article->description ?? ""}}</textarea>

    <hr/>

    <label for="">Мета заголовок</label>
    <input type="text" class="form-control" name="meta_title" placeholder="Мета заголовок"
           value="{{$article->meta_title ?? ""}}">

    <label for="">Мета описание</label>
    <input type="text" class="form-control" name="meta_description" placeholder="Мета описание"
           value="{{$article->meta_description ?? ""}}">

    <label for="">Ключевые слова</label>
    <input type="text" class="form-control" name="meta_keyword" placeholder="Ключевые слова, через запятую"
           value="{{$article->meta_keyword ?? ""}}">

    <hr/>

    <input class="btn btn-dark" type="submit" value="Сохранить">
</div>

Laravel/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Приветствуем {{ Auth::user()->name }}!</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        Вы вошли в систему!
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

Laravel/resources/views/layout.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Тестовый блог на Laravel.">

    <title>Блог на Laravel | Blog on Laravel </title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <link href="css/blog.css" rel="stylesheet">
</head>

<body>
<script src="{{ asset('/vendor/unisharp/laravel-ckeditor/ckeditor.js')}}"></script>
<script>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date();
        a = s.createElement(o),
            m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
    })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-4481610-59', 'auto');
    ga('send', 'pageview');

</script>

@include('layouts.app')

@include('layouts.footer')

</body>
</html>

Laravel/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Тестовый блог на Laravel.">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="{{ asset('/vendor/unisharp/laravel-ckeditor/ckeditor.js')}}"></script>
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-4481610-59', 'auto');
        ga('send', 'pageview');

    </script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <link href="css/blog.css" rel="stylesheet">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<div id="app">
    <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
        <div class="col-4 text-center">
            <a class="blog-header-logo text-dark" href="https://test.laravel.local">Blog on Laravel</a>
        </div>


        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="container">
            <div class="nav-scroller py-1">
                <nav class="nav d-flex justify-content-between float-left">
                    <a class="p-2 text-muted" href="/">Главная</a>
                    <a class="p-2 text-muted" href="{{route('admin.article.create')}}">Создать новость</a>
                    <a class="p-2 text-muted" href="/admin/article">Список новостей</a>
                </nav>
            </div>
        </div>
        <div class="container">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">

            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('Войти') }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('register') }}">{{ __('Регистрация') }}</a>
                    </li>
                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                {{ __('Выйти') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
        </div>
    </nav>
</div>



<main class="py-4">
    @yield('content')
</main>
</html>

Laravel/resources/views/layouts/footer.blade.php
<footer class="blog-footer">
    <p>My telegram
        <a href="https://t.me/Sergey_s_pol">@Sergey_s_pol</a>.
    </p>
    <p>
        <a href="#menu">Back to top</a>
    </p>
</footer>

Laravel/resources/views/layouts/nav.blade.php
<div class="container">
    <header class="blog-header py-3" id="menu">
        <div class="row flex-nowrap justify-content-between align-items-center">
            <div class="col-4 pt-1">
                <a class="text-muted"></a>
            </div>
            <div class="col-4 text-center">
                <a class="blog-header-logo text-dark" href="https://test.laravel.local">Blog on Laravel</a>
            </div>
            <div class="col-4 d-flex justify-content-end align-items-center">
                <a class="btn btn-sm btn-outline-secondary m-1 w-25" href="login">Войти</a>
                <a class="btn btn-sm btn-outline-secondary m-1 w-30" href="register">Регистрация</a>
            </div>
        </div>
    </header>
</div>

<div class="container">
    <div class="nav-scroller py-1 mb-2">
        <nav class="nav d-flex justify-content-between float-left">
            <a class="p-2 text-muted" href="/">Главная</a>
            <a class="p-2 text-muted" href="{{route('admin.article.create')}}">Создать новость</a>
            <a class="p-2 text-muted" href="/admin/article">Список новостей</a>
        </nav>
    </div>
</div>

Laravel/resources/views/mail.blade.php
Тестовое письмо!

Laravel/resources/views/pagination.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

</head>
<body>
<div class="container">
<table class="table">
    <thead class="thead-dark">
    <tr>
        <th scope="col">№</th>
        <th scope="col">Name</th>
        <th scope="col">E-mail</th>
    </tr>
    </thead>
    <tbody>
    @foreach($posts as $post)
    <tr>
        <td>{{ $post->index +1 }}</td>
        <td>{{ $post->name }}</td>
        <td>{{ $post->e-mail }}</td>
    </tr>
    @endforeach
    </tbody>
</table>
    {{ $posts->links() }}
</div>
</body>
</html>

Laravel/resources/views/posts/index.blade.php
@extends('layout')

@section('content')

    <div class="container">
        <div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
            <div class="col-md-6 px-0">
                <h1 class="display-4 font-italic">I present to you a blog written on Laravel</h1>
                <p class="lead my-3">Представляю вам блог написанный на Laravel</p>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="container text-center"><p>Общее кол-во новостей: {{$count_articles}}</p></div>
        <div class="row mb-2">

            @foreach($articles as $article)

                <div class="col-md-6">
                    <div class="card flex-md-row mb-4 box-shadow h-md-150">
                        <div class="card-body d-flex flex-column align-items-start">
                            <h3 class="mb-0">
                                <a class="text-dark"
                                   href="{{route('admin.article.edit', $article)}}">{{$article->title}}</a>
                            </h3>
                            <p class="card-text mb-auto">{{$article->description_short}}...</p>
                            <a href="{{route('admin.article.edit', $article)}}">Читать продолжение...</a>
                        </div>
                    </div>
                </div>

            @endforeach

        </div>
    </div>


    <div class="container">
        <table class="table">
            <tfoot>
            <td>
                <ul class="float-right">
                    {{$articles->links()}}
                </ul>
            </td>
            </tfoot>
        </table>
    </div>

@endsection